name = "MLS"
uuid = "c1c04a98-9b22-4c5e-a8f1-f5333ae318dd"
authors = ["Steve Frank <saf@stevefrank.org>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1.5.0"
DifferentialEquations = "7.13.0"
Plots = "1.40.8"
